"""Add some Pitch columns

Revision ID: 0f528ae61ecc
Revises: e2016d561d82
Create Date: 2024-12-07 15:24:09.228289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f528ae61ecc'
down_revision: Union[str, None] = 'e2016d561d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('is_ball', sa.Boolean(), nullable=False))
    op.add_column('pitches', sa.Column('is_strike', sa.Boolean(), nullable=False))
    op.add_column('pitches', sa.Column('is_foul', sa.Boolean(), nullable=False))
    op.add_column('pitches', sa.Column('is_in_play', sa.Boolean(), nullable=False))
    op.add_column('pitches', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'details')
    op.drop_column('pitches', 'is_in_play')
    op.drop_column('pitches', 'is_foul')
    op.drop_column('pitches', 'is_strike')
    op.drop_column('pitches', 'is_ball')
    # ### end Alembic commands ###
