"""Remove created_at/updated_at where unnecessary

Revision ID: 12ff0f461eb8
Revises: 693631df5adb
Create Date: 2025-03-16 11:56:42.809982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12ff0f461eb8'
down_revision: Union[str, None] = '693631df5adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_abdetails_created_at', table_name='at_bat_details')
    op.drop_index('idx_abdetails_updated_at', table_name='at_bat_details')
    op.drop_column('at_bat_details', 'updated_at')
    op.drop_column('at_bat_details', 'created_at')
    op.drop_index('idx_at_bat_created_at', table_name='at_bats')
    op.drop_index('idx_at_bat_updated_at', table_name='at_bats')
    op.drop_column('at_bats', 'updated_at')
    op.drop_column('at_bats', 'created_at')
    op.drop_index('idx_pitch_created_at', table_name='pitches')
    op.drop_index('idx_pitch_updated_at', table_name='pitches')
    op.drop_column('pitches', 'updated_at')
    op.drop_column('pitches', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('idx_pitch_updated_at', 'pitches', ['updated_at'], unique=False)
    op.create_index('idx_pitch_created_at', 'pitches', ['created_at'], unique=False)
    op.add_column('at_bats', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('at_bats', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('idx_at_bat_updated_at', 'at_bats', ['updated_at'], unique=False)
    op.create_index('idx_at_bat_created_at', 'at_bats', ['created_at'], unique=False)
    op.add_column('at_bat_details', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('at_bat_details', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('idx_abdetails_updated_at', 'at_bat_details', ['updated_at'], unique=False)
    op.create_index('idx_abdetails_created_at', 'at_bat_details', ['created_at'], unique=False)
    # ### end Alembic commands ###
