"""Added mlb_id cols to AtBats

Revision ID: 156a3808f9d6
Revises: 4e9ff1c30df1
Create Date: 2024-12-01 12:27:07.061287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156a3808f9d6'
down_revision: Union[str, None] = '4e9ff1c30df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('at_bats', sa.Column('game_mlb_id', sa.Integer(), nullable=True))
    op.add_column('at_bats', sa.Column('pitcher_mlb_id', sa.Integer(), nullable=True))
    op.add_column('at_bats', sa.Column('batter_mlb_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'at_bats', 'players', ['batter_mlb_id'], ['mlb_id'])
    op.create_foreign_key(None, 'at_bats', 'players', ['pitcher_mlb_id'], ['mlb_id'])
    op.create_foreign_key(None, 'at_bats', 'games', ['game_mlb_id'], ['mlb_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'at_bats', type_='foreignkey')
    op.drop_constraint(None, 'at_bats', type_='foreignkey')
    op.drop_constraint(None, 'at_bats', type_='foreignkey')
    op.drop_column('at_bats', 'batter_mlb_id')
    op.drop_column('at_bats', 'pitcher_mlb_id')
    op.drop_column('at_bats', 'game_mlb_id')
    # ### end Alembic commands ###
