"""Add player fields

Revision ID: 157ea81f06b3
Revises: e368057fb1bd
Create Date: 2024-12-21 09:48:47.002991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157ea81f06b3'
down_revision: Union[str, None] = 'e368057fb1bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('birth_city', sa.String(), nullable=True))
    op.add_column('players', sa.Column('birth_country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'birth_country')
    op.drop_column('players', 'birth_city')
    # ### end Alembic commands ###
