"""Add created_at/updated_at fields

Revision ID: 2951f7949746
Revises: 157ea81f06b3
Create Date: 2025-02-23 20:19:48.559923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2951f7949746'
down_revision: Union[str, None] = '157ea81f06b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('at_bat_details', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('at_bat_details', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('at_bats', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('at_bats', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('players', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('players', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('teams', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('teams', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'updated_at')
    op.drop_column('teams', 'created_at')
    op.drop_column('players', 'updated_at')
    op.drop_column('players', 'created_at')
    op.drop_column('pitches', 'updated_at')
    op.drop_column('pitches', 'created_at')
    op.drop_column('games', 'updated_at')
    op.drop_column('games', 'created_at')
    op.drop_column('at_bats', 'updated_at')
    op.drop_column('at_bats', 'created_at')
    op.drop_column('at_bat_details', 'updated_at')
    op.drop_column('at_bat_details', 'created_at')
    # ### end Alembic commands ###
