"""Added game_type field

Revision ID: 322b12f0fa43
Revises: c2feea02bb14
Create Date: 2024-10-20 20:09:16.646999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '322b12f0fa43'
down_revision: Union[str, None] = 'c2feea02bb14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'game_type')
    # ### end Alembic commands ###
