"""At bats table

Revision ID: 3fae86587732
Revises: 45dd63efe6ba
Create Date: 2024-10-15 20:30:49.012612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fae86587732'
down_revision: Union[str, None] = '45dd63efe6ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('at_bats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mlb_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('call', sa.String(), nullable=False),
    sa.Column('score_before_at_bat', sa.Integer(), nullable=False),
    sa.Column('score_after_at_bat', sa.Integer(), nullable=False),
    sa.Column('outs', sa.Integer(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=False),
    sa.Column('top', sa.Boolean(), nullable=False),
    sa.Column('r1b', sa.Boolean(), nullable=False),
    sa.Column('r2b', sa.Boolean(), nullable=False),
    sa.Column('r3b', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['batter_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mlb_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('at_bats')
    # ### end Alembic commands ###
