"""Added Game.mlb_id index

Revision ID: 4111d854d5cf
Revises: 156a3808f9d6
Create Date: 2024-12-01 12:33:27.679445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4111d854d5cf'
down_revision: Union[str, None] = '156a3808f9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_game_mlb_id', 'games', ['mlb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_game_mlb_id', table_name='games')
    # ### end Alembic commands ###
