"""Add Game.season index

Revision ID: 4c4d82b58be4
Revises: efadf19f080d
Create Date: 2024-12-09 12:07:09.774754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4d82b58be4'
down_revision: Union[str, None] = 'efadf19f080d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_game_season', 'games', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_game_season', table_name='games')
    # ### end Alembic commands ###
