"""Change AtBatDetails game_id column name

Revision ID: 4e9ff1c30df1
Revises: 50d5615f4377
Create Date: 2024-11-30 13:57:18.452463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9ff1c30df1'
down_revision: Union[str, None] = '50d5615f4377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('at_bat_details', sa.Column('game_mlb_id', sa.Integer(), nullable=True))
    op.drop_constraint('at_bat_details_game_id_fkey', 'at_bat_details', type_='foreignkey')
    op.create_foreign_key(None, 'at_bat_details', 'games', ['game_mlb_id'], ['mlb_id'])
    op.drop_column('at_bat_details', 'game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('at_bat_details', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'at_bat_details', type_='foreignkey')
    op.create_foreign_key('at_bat_details_game_id_fkey', 'at_bat_details', 'games', ['game_id'], ['mlb_id'])
    op.drop_column('at_bat_details', 'game_mlb_id')
    # ### end Alembic commands ###
