"""Add columns to AtBatDetails

Revision ID: 50d5615f4377
Revises: 761b266cb2d9
Create Date: 2024-11-30 12:19:00.005586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d5615f4377'
down_revision: Union[str, None] = '761b266cb2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('at_bat_details', sa.Column('game_id', sa.Integer(), nullable=True))
    op.add_column('at_bat_details', sa.Column('sport_id', sa.Integer(), nullable=True))
    op.add_column('at_bat_details', sa.Column('season', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'at_bat_details', 'games', ['game_id'], ['mlb_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'at_bat_details', type_='foreignkey')
    op.drop_column('at_bat_details', 'season')
    op.drop_column('at_bat_details', 'sport_id')
    op.drop_column('at_bat_details', 'game_id')
    # ### end Alembic commands ###
