"""Corrected mlb_id constraints

Revision ID: 559e318f49df
Revises: 322b12f0fa43
Create Date: 2024-10-20 22:38:58.354411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559e318f49df'
down_revision: Union[str, None] = '322b12f0fa43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('home_team_mlb_id', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('away_team_mlb_id', sa.Integer(), nullable=False))
    op.drop_constraint('games_home_team_id_fkey', 'games', type_='foreignkey')
    op.drop_constraint('games_away_team_id_fkey', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'teams', ['away_team_mlb_id'], ['mlb_id'])
    op.create_foreign_key(None, 'games', 'teams', ['home_team_mlb_id'], ['mlb_id'])
    op.drop_column('games', 'away_team_id')
    op.drop_column('games', 'home_team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('home_team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('away_team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('games_away_team_id_fkey', 'games', 'teams', ['away_team_id'], ['id'])
    op.create_foreign_key('games_home_team_id_fkey', 'games', 'teams', ['home_team_id'], ['id'])
    op.drop_column('games', 'away_team_mlb_id')
    op.drop_column('games', 'home_team_mlb_id')
    # ### end Alembic commands ###
