"""Add sport id to games

Revision ID: 6538000aa20d
Revises: 2ed0d867c07c
Create Date: 2024-11-09 23:12:42.591366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6538000aa20d'
down_revision: Union[str, None] = '2ed0d867c07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('at_bat_details', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('at_bats', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('at_bats', 'pitcher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('at_bats', 'batter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('games', sa.Column('sport_id', sa.Integer(), nullable=True))
    op.alter_column('games', 'game_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('games', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('games', 'home_team_mlb_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('games', 'away_team_mlb_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pitches', 'at_bat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('players', 'primary_position_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('players', 'primary_position',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('players', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('players', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('teams', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('teams', 'hometown',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('teams', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('teams', 'hometown',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teams', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('players', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('players', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('players', 'primary_position',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('players', 'primary_position_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('players', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('pitches', 'at_bat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('games', 'away_team_mlb_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('games', 'home_team_mlb_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('games', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('games', 'game_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('games', 'sport_id')
    op.alter_column('at_bats', 'batter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('at_bats', 'pitcher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('at_bats', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('at_bat_details', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
