"""Add created_at/updated_at indexes on pitches table

Revision ID: 693631df5adb
Revises: d98ef620f68b
Create Date: 2025-03-15 16:37:54.780721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693631df5adb'
down_revision: Union[str, None] = 'd98ef620f68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_pitch_created_at', 'pitches', ['created_at'], unique=False)
    op.create_index('idx_pitch_updated_at', 'pitches', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pitch_updated_at', table_name='pitches')
    op.drop_index('idx_pitch_created_at', table_name='pitches')
    # ### end Alembic commands ###
