"""Make some Player columns nullable

Revision ID: 71e5ebb47238
Revises: 0617f9d218ab
Create Date: 2024-12-06 11:58:14.593031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e5ebb47238'
down_revision: Union[str, None] = '0617f9d218ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'is_player',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'is_player',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
