"""Modify AtBat columns

Revision ID: 85cfd3a8f9f4
Revises: fa33a0cc9da3
Create Date: 2024-12-01 16:18:45.261102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85cfd3a8f9f4'
down_revision: Union[str, None] = 'fa33a0cc9da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('at_bats', sa.Column('at_bat_index', sa.Integer(), nullable=False))
    op.add_column('at_bats', sa.Column('has_out', sa.Boolean(), nullable=False))
    op.add_column('at_bats', sa.Column('balls', sa.Integer(), nullable=False))
    op.add_column('at_bats', sa.Column('strikes', sa.Integer(), nullable=False))
    op.add_column('at_bats', sa.Column('total_pitch_count', sa.Integer(), nullable=False))
    op.add_column('at_bats', sa.Column('is_top_inning', sa.Boolean(), nullable=False))
    op.add_column('at_bats', sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('at_bats', sa.Column('rbi', sa.Integer(), nullable=False))
    op.add_column('at_bats', sa.Column('event_type', sa.String(), nullable=False))
    op.add_column('at_bats', sa.Column('is_scoring_play', sa.Boolean(), nullable=False))
    op.add_column('at_bats', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('at_bats', 'top')
    op.drop_column('at_bats', 'score_before_at_bat')
    op.drop_column('at_bats', 'call')
    op.drop_column('at_bats', 'score_after_at_bat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('at_bats', sa.Column('score_after_at_bat', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('at_bats', sa.Column('call', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('at_bats', sa.Column('score_before_at_bat', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('at_bats', sa.Column('top', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('at_bats', 'details')
    op.drop_column('at_bats', 'is_scoring_play')
    op.drop_column('at_bats', 'event_type')
    op.drop_column('at_bats', 'rbi')
    op.drop_column('at_bats', 'result')
    op.drop_column('at_bats', 'is_top_inning')
    op.drop_column('at_bats', 'total_pitch_count')
    op.drop_column('at_bats', 'strikes')
    op.drop_column('at_bats', 'balls')
    op.drop_column('at_bats', 'has_out')
    op.drop_column('at_bats', 'at_bat_index')
    # ### end Alembic commands ###
