"""Added fields to players table

Revision ID: 97d54ae443f7
Revises: 11a48fe65b10
Create Date: 2024-10-12 13:03:59.522463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d54ae443f7'
down_revision: Union[str, None] = '11a48fe65b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('players', sa.Column('is_player', sa.Boolean(), nullable=False))
    op.add_column('players', sa.Column('throws', sa.String(), nullable=True))
    op.add_column('players', sa.Column('bats', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'bats')
    op.drop_column('players', 'throws')
    op.drop_column('players', 'is_player')
    op.drop_column('players', 'full_name')
    # ### end Alembic commands ###
