"""Remove post_season_game field

Revision ID: c2feea02bb14
Revises: 20416110c483
Create Date: 2024-10-20 20:07:40.752413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2feea02bb14'
down_revision: Union[str, None] = '20416110c483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'post_season_game')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('post_season_game', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
