"""Add sport id to teams

Revision ID: c6def68ae504
Revises: 6538000aa20d
Create Date: 2024-11-10 11:52:15.051055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6def68ae504'
down_revision: Union[str, None] = '6538000aa20d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('sport_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'sport_id')
    # ### end Alembic commands ###
