"""Pitches table

Revision ID: cd35b9396032
Revises: 3fae86587732
Create Date: 2024-10-15 20:34:55.154394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd35b9396032'
down_revision: Union[str, None] = '3fae86587732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ball_count', sa.Integer(), nullable=False),
    sa.Column('strike_count', sa.Integer(), nullable=False),
    sa.Column('pitch_type_code', sa.String(), nullable=False),
    sa.Column('pitch_type_description', sa.String(), nullable=False),
    sa.Column('call_code', sa.String(), nullable=False),
    sa.Column('call_description', sa.String(), nullable=False),
    sa.Column('is_out', sa.Boolean(), nullable=False),
    sa.Column('start_speed', sa.Float(), nullable=False),
    sa.Column('zone', sa.Integer(), nullable=False),
    sa.Column('pitch_index', sa.Integer(), nullable=False),
    sa.Column('at_bat_id', sa.Integer(), nullable=False),
    sa.Column('r1b', sa.Boolean(), nullable=False),
    sa.Column('r2b', sa.Boolean(), nullable=False),
    sa.Column('r3b', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['at_bat_id'], ['at_bats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitches')
    # ### end Alembic commands ###
