"""Add created_at/updated_at indexes on tables

Revision ID: d98ef620f68b
Revises: 1ce0a5774253
Create Date: 2025-03-15 16:34:13.692913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd98ef620f68b'
down_revision: Union[str, None] = '1ce0a5774253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_abdetails_created_at', 'at_bat_details', ['created_at'], unique=False)
    op.create_index('idx_abdetails_game_mlb_id', 'at_bat_details', ['game_mlb_id'], unique=False)
    op.create_index('idx_abdetails_updated_at', 'at_bat_details', ['updated_at'], unique=False)
    op.create_index('idx_at_bat_created_at', 'at_bats', ['created_at'], unique=False)
    op.create_index('idx_at_bat_game_id', 'at_bats', ['game_id'], unique=False)
    op.create_index('idx_at_bat_game_mlb_id', 'at_bats', ['game_mlb_id'], unique=False)
    op.create_index('idx_at_bat_updated_at', 'at_bats', ['updated_at'], unique=False)
    op.create_index('idx_game_created_at', 'games', ['created_at'], unique=False)
    op.create_index('idx_game_updated_at', 'games', ['updated_at'], unique=False)
    op.create_index('idx_player_updated_at', 'players', ['updated_at'], unique=False)
    op.create_index('idx_team_created_at', 'teams', ['created_at'], unique=False)
    op.create_index('idx_team_updated_at', 'teams', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_team_updated_at', table_name='teams')
    op.drop_index('idx_team_created_at', table_name='teams')
    op.drop_index('idx_player_updated_at', table_name='players')
    op.drop_index('idx_game_updated_at', table_name='games')
    op.drop_index('idx_game_created_at', table_name='games')
    op.drop_index('idx_at_bat_updated_at', table_name='at_bats')
    op.drop_index('idx_at_bat_game_mlb_id', table_name='at_bats')
    op.drop_index('idx_at_bat_game_id', table_name='at_bats')
    op.drop_index('idx_at_bat_created_at', table_name='at_bats')
    op.drop_index('idx_abdetails_updated_at', table_name='at_bat_details')
    op.drop_index('idx_abdetails_game_mlb_id', table_name='at_bat_details')
    op.drop_index('idx_abdetails_created_at', table_name='at_bat_details')
    # ### end Alembic commands ###
