"""Make some Pitch columns nullable

Revision ID: e2016d561d82
Revises: 71e5ebb47238
Create Date: 2024-12-07 12:18:29.244874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2016d561d82'
down_revision: Union[str, None] = '71e5ebb47238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pitches', 'r1b',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pitches', 'r2b',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pitches', 'r3b',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pitches', 'r3b',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pitches', 'r2b',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pitches', 'r1b',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
