"""Add indexes

Revision ID: e368057fb1bd
Revises: 4c4d82b58be4
Create Date: 2024-12-09 12:11:41.832653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e368057fb1bd'
down_revision: Union[str, None] = '4c4d82b58be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_at_bat_batter_id', 'at_bats', ['batter_id'], unique=False)
    op.create_index('idx_at_bat_batter_mlb_id', 'at_bats', ['batter_mlb_id'], unique=False)
    op.create_index('idx_at_bat_pitcher_id', 'at_bats', ['pitcher_id'], unique=False)
    op.create_index('idx_at_bat_pitcher_mlb_id', 'at_bats', ['pitcher_mlb_id'], unique=False)
    op.create_index('idx_at_bat_sport_id', 'at_bats', ['sport_id'], unique=False)
    op.create_index('idx_pitch_at_bat_id', 'pitches', ['at_bat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pitch_at_bat_id', table_name='pitches')
    op.drop_index('idx_at_bat_sport_id', table_name='at_bats')
    op.drop_index('idx_at_bat_pitcher_mlb_id', table_name='at_bats')
    op.drop_index('idx_at_bat_pitcher_id', table_name='at_bats')
    op.drop_index('idx_at_bat_batter_mlb_id', table_name='at_bats')
    op.drop_index('idx_at_bat_batter_id', table_name='at_bats')
    # ### end Alembic commands ###
