"""Drop AtBat.mlb_id

Revision ID: fa33a0cc9da3
Revises: 635c49c16857
Create Date: 2024-12-01 14:28:47.607449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa33a0cc9da3'
down_revision: Union[str, None] = '635c49c16857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('at_bats_mlb_id_key', 'at_bats', type_='unique')
    op.drop_column('at_bats', 'mlb_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('at_bats', sa.Column('mlb_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('at_bats_mlb_id_key', 'at_bats', ['mlb_id'])
    # ### end Alembic commands ###
